id: httpget
functions:
- id: httprequest
  image: vorteil/request:v2
states:
- id: getter 
  type: action
  action:
    function: httprequest
    input: '{
      "method": "GET",
      "url": "https://www.example.com/",
    }'
