id: action
description: A simple 'action' state that sends a get request"
functions:
- id: get
  type: reusable
  image: vorteil/request:v6
states:
- id: getter 
  type: action
  action:
    function: get
    input: 
      method: "GET"
      url: "https://jsonplaceholder.typicode.com/todos/1"
