name: amazon-sns
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version Tag'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.15
    - name: Create App-Dir
      run: mkdir amazonsns
    - name: Move Dockerfile
      run: cp amazon-sns/Dockerfile ./amazonsns/
    - name: Move Readme
      run: cp amazon-sns/README.md ./amazonsns/
    - name:
      run: cd amazon-sns && CGO_ENABLED=0 go build -o ../amazonsns/amazon-sns main.go
    - uses: actions/upload-artifact@v2
      with:
        name: amazonsns
        path: amazonsns
  releases:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download amazonsns Application
      uses: actions/download-artifact@v2
      with:
        name: amazonsns
        path: amazonsns
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: chmod +x amazonsns binary
      run: sudo chmod +x ./amazonsns/amazon-sns
    
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: vorteil/amazon-sns:latest
        context: .
        file: ./amazonsns/Dockerfile
        platforms: linux/amd64
    
    - name: Build and Push version
      id: docker_build2
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: vorteil/amazon-sns:${{ github.event.inputs.tags }}
        context: .
        file: ./amazonsns/Dockerfile
        platforms: linux/amd64
    
    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vorteil/amazon-sns
        readme: "./amazonsns/README.md"