name: gcplog
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version Tag'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.15
    - name: Create App-Dir
      run: mkdir gcpprint
    - name: Move Dockerfile
      run: cp gcplog/Dockerfile ./gcpprint/
    - name: Move Readme
      run: cp gcplog/README.md ./gcpprint/
    - name:
      run: cd gcplog && CGO_ENABLED=0 go build -o ../gcpprint/gcpprint main.go
    - uses: actions/upload-artifact@v2
      with:
        name: gcpprint
        path: gcpprint
  releases:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download gcpprint Application
      uses: actions/download-artifact@v2
      with:
        name: gcpprint
        path: gcpprint
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: chmod +x gcpprint binary
      run: sudo chmod +x ./gcpprint/gcpprint
    
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: vorteil/gcplog:latest
        context: .
        file: ./gcpprint/Dockerfile
        platforms: linux/amd64
    
    - name: Build and Push version
      id: docker_build2
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: vorteil/gcplog:${{ github.event.inputs.tags }}
        context: .
        file: ./gcpprint/Dockerfile
        platforms: linux/amd64
    
    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vorteil/gcplog
        readme: "./gcpprint/README.md"