name: generate-markdown
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cli to generate markdown
      run : |
        cd cli && GITHUB_SHA=${GITHUB_SHA} SHA=$(echo ${GITHUB_SHA} | cut -c1-8) go run main.go
        cd ../ && rm readme.md
        cp /tmp/newreadme.md readme.md
    - name: Commit & Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}