name: googlechat
on:
  workflow_dispatch:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Create-AppDir
      run: mkdir googlemsg
    - name: Move-Dockerfile
      run: cp googlechat/Dockerfile ./googlemsg/
    - name: Move-Readme
      run: cp googlechat/README.md ./googlemsg/      
    - name: Find-Govaluate
      run: go get github.com/Knetic/govaluate
    - name: Build
      run: CGO_ENABLED=0 go build -o ./googlemsg/googlemsg googlechat/main.go
    - uses: actions/upload-artifact@v2
      with:
        name: googlemsg
        path: googlemsg
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download googlemsg Application
      uses: actions/download-artifact@v2
      with:
        name: googlemsg
        path: googlemsg
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vorteil/googlemsg:latest
        context: .
        file: ./googlemsg/Dockerfile
        platforms: linux/amd64

    - name: Build and Push
      id: docker_build2
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vorteil/googlemsg:${{ steps.get_version.outputs.VERSION }}
        context: .
        file: ./googlemsg/Dockerfile
        platforms: linux/amd64

    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vorteil/googlemsg
        readme: "./googlemsg/README.md"