name: Store
on: 
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Create-AppDir
      run: mkdir store
    
    - name: Move-Dockerfile
      run: cp googlepusher/Dockerfile ./store/
    - name: Move-Request-Readme
      run: cp googlepusher/readme.md ./store/
    
    - name: Build
      run: CGO_ENABLED=0 go build -o ./store/store googlerpusher/googlepusher.go
    
    - uses: actions/upload-artifact@v2
      with:
        name: store
        path: store

release:
  needs: build
  runs-on: ubuntu-latest
  steps:
  - name: Download Store Application
    uses: actions/download-artifact@v2
    with:
      name: store
      path: store
  - name: Setup Docker Buildx
    uses: docker/setup-buildx-action@v1
  
  - name: Login to Dockerhub
    uses: docker/login-action@v1
    with: 
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    
  - name: lsCheck
    run: ls -la ./store
  - name: Build and Push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      push: true
      tags: vorteil/store:latest
      context: .
      file: ./store/Dockerfile
      platforms: linux/amd64