name: lambdainvoke
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Create-AppDir
      run: mkdir lambda
    - name: Move-Dockerfile
      run: cp lambdainvoke/Dockerfile ./lambda/
    - name: Move-lambda-Readme
      run: cp lambdainvoke/readme.md ./lambda/     
    - name: Find-Direktivapps
      run: go get github.com/vorteil/direktiv-apps/pkg/direktivapps
    - name: Find-AWS-Dependencies
      run: go get  github.com/aws/aws-sdk-go/aws  github.com/aws/aws-sdk-go/aws/credentials github.com/aws/aws-sdk-go/aws/session github.com/aws/aws-sdk-go/service/lambda
    - name: Build
      run: CGO_ENABLED=0 go build -o ./lambda/lambda lambdainvoke/main.go
    - uses: actions/upload-artifact@v2
      with:
        name: lambda
        path: lambda

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download lambda Application
      uses: actions/download-artifact@v2
      with:
        name: lambda
        path: lambda


    - name: chmod +x lambda binary
      run: sudo chmod +x ./lambda/lambda    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  
    
    # - name: Add SHORT_SHA env property with commit short sha
    #   run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    # - name: Get the version
    #   id: get_version
    #   run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vorteil/lambda:latest
        context: .
        file: ./lambda/Dockerfile
        platforms: linux/amd64

    - name: Build and Push
      id: docker_build2
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vorteil/lambda:${{ github.event.inputs.tags }}
        context: .
        file: ./lambda/Dockerfile
        platforms: linux/amd64

    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vorteil/lambda
        readme: "./lambda/readme.md"