name: Request
on:
  push:
    branches: ["master"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: marceloprado/has-changed-path@v1
      id: changed-requester
      with:
        paths: .
      env:
          SOURCE: requester
    - shell: bash
      if: steps.changed-main.outputs.changed == 'true'
      run: |
        true > changed-paths
    - shell: bash
      if: steps.changed-main.outputs.changed == 'false'
      run: |
        false > changed-paths
    - name: Upload whether files have changed for directory
      uses: actions/upload-artifact@v2
      with:
        name: request-changed
        path: changed-paths    
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Download change check
      uses: actions/download-artifact@v2
      with:
        name: request-changed
        path: changed-paths
    - shell: bash
      run: |
          value=`cat request-changed`
         
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Create-AppDir
      run: mkdir request
    - name: Move-Dockerfile
      run: cp requester/Dockerfile ./request/
    - name: Move-Request-Readme
      run: cp requester/readme.md ./request/      
    - name: Build
      run: CGO_ENABLED=0 go build -o ./request/request requester/main.go
    
    - uses: actions/upload-artifact@v2
      with:
        name: request
        path: request

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Request Application
      uses: actions/download-artifact@v2
      with:
        name: request
        path: request

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  
    
    - name: lsCheck
      run: ls -la ./request

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vorteil/request
        context: .
        file: ./request/Dockerfile
        platforms: linux/amd64
