name: Build-Apps
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Move-Dockerfile
      run: mv requester/Dockerfile ../
      
    - name: Build
      run: CGO_ENABLED=0 go build -o /request requester/main.go
  release:
      runs-on: ubuntu-latest
      steps:
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true    
