name: Build-Apps
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
   
    - name: Create-App-Dir
      run: mkdir app

    - name: Move-Dockerfile
      run: mv requester/Dockerfile ../app
      
    - name: Build
      run: CGO_ENABLED=0 go build -o ./app/request requester/main.go
    
    - uses: actions/upload-artifact@v2
      with:
        name: request-app
        path: ./app

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Request-APP
      uses: actions/download-artifact@v2
      with:
        name: request-app
    - name: Push to DockerHub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./app/Dockerfile
        tag_with_ref: true    
